### ISSUE TITLE
Class not found on server start

### ISSUE THREAD

**Issue by kz5ee** [manuelgu/DiscordMC#10] opened 2016-10-20 16:55 UTC
Version 1.4.4

```
[ERROR]: Error occurred while enabling DiscordMC v1.4.4 (Is it up to date?)java.lang.NoClassDefFoundError: gnu/trove/set/hash/THashSet  at 
eu.manuelgu.discordmc.DiscordMC.onEnable(DiscordMC.java:83) ~[?:?]  at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) 
~[server.jar:git-Bukkit-8e5e90d]    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:329) [server.jar:git-Bukkit-8e5e90d]  at 
org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [server.jar:git-Bukkit-8e5e90d]    at 
org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugin(CraftServer.java:358) [server.jar:git-Bukkit-8e5e90d]  at 
org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:320) [server.jar:git-Bukkit-8e5e90d] at 
net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:404) [server.jar:git-Bukkit-8e5e90d]   at 
net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:369) [server.jar:git-Bukkit-8e5e90d]   at 
net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:324) [server.jar:git-Bukkit-8e5e90d]   at 
net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:243) [server.jar:git-Bukkit-8e5e90d]    at
 net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:514) [server.jar:git-Bukkit-8e5e90d]    at java.lang.Thread.run(Thread.java:745)
 [?:1.8.0_74]Caused by: java.lang.ClassNotFoundException: gnu.trove.set.hash.THashSet   at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_74] at 
 org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:77) ~[server.jar:git-Bukkit-8e5e90d] at 
 org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62) ~[server.jar:git-Bukkit-8e5e90d] at 
 java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_74]    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_74]  ... 12 more
 >
```

Is there a dependency that I need installed on my server to make this work?

**Comment by manuelgu** [comment] 2016-11-14 17:34
Cannot reproduce. Still an issue? Please also provide a `/discord debug`

**Comment by k80w** [comment] 2017-01-02 03:36
Same problem here, running the latest version of Spigot on Ubuntu 14.04 and Arch Linux 2017.01.01. Running the `/discord` command returns the `/discord <args>` message regardless of what arguments I give it.

**Comment by manuelgu** [comment] 2017-01-02 11:56
@dnaf Is it also giving a `NoClassDefFoundError` for `gnu/trove/set/hash/THashSet`?

**Comment by k80w** [comment] 2017-01-03 05:55
@manuelgu Yep. I'm assuming I need to install the Trove library, but I know nothing about Java development and I can't find much about Trove.

**Comment by manuelgu** [comment] 2017-01-04 21:21
@dnaf @kz5ee is this any better?

[DiscordMC-1.4.9-SNAPSHOT.zip](https://github.com/manuelgu/DiscordMC/files/685934/DiscordMC-1.4.9-SNAPSHOT.zip)

**Comment by k80w** [comment] 2017-01-05 04:03
@manuelgu Works fine! Thanks!

**Comment by manuelgu** [comment] 2017-01-05 08:32
@dnaf Awesome, will be fixed in the next release then!

**Closed as completed by manuelgu** 2017-01-05 08:32 UTC

**Comment by egro5** [comment] 2017-07-17 18:42
I'm having a similar error on my server running DiscordMC 1.4.12, Spigot 1.11.2, and Ubuntu 16.04.2

Any suggestions?
