### ISSUE TITLE
Logout messages don't push to Discord

### ISSUE THREAD

**Issue by gauderkd** [manuelgu/DiscordMC#3] opened 2016-06-15 20:36 UTC
This is despite logout messages being set to "true" in the config file. All other messages are sent to Discord correctly.

**Comment by manuelgu** [comment] 2016-06-15 20:44
Cannot reproduce.

Do you mind attaching a `/discord debug`?

**Comment by gauderkd** [comment] 2016-06-15 23:22
Here you are:
http://hastebin.com/fixetisahi

_configFile: http://hastebin.com/rodohirexa
isReady: true
guilds:
  'LittleGadgetServer'
botName: Bot-Craft
channels:
  minecraftToDiscord: minecraftdraconis, draconisserverlog
  discordToMinecraft: general, minecraftdraconis_

**Comment by gauderkd** [comment] 2016-06-15 23:24
I just noticed, if I OP myself in my server, I get the logout message. Which means I'm having a permission issue? But the permission should be with chat/login/death as well through `discordmc.chat` no?

**Comment by manuelgu** [comment] 2016-06-16 08:19
Looks like it. The checks are all the same for login/logout/death to see if the player has the correct permissions. 

Can you try to temporarily remove the Slack integration plugin and see if that helps any?

I remember an issue from back in the days when it was not possible to check for player permissions when he is technically already disconnected. This might be related to your permissions plugin, my tests are all done with PermissionsEx. I'll get a test setup working and report back.

**Comment by manuelgu** [comment] 2016-06-16 08:26
Turns out I never tested this plugin with PermissionsEx. Neither with PermissionsEx nor with PermissionsBukkit the logout messages are getting delivered.

I'll investigate this issue further and will look for good caching solutions.

**Comment by gauderkd** [comment] 2016-06-16 15:26
Just for the sake of it, I can confirm removing the Slack plugin did not change the situation. On the bright side, I guess there are no issues with Slack compatibility.

**Comment by manuelgu** [comment] 2016-10-01 14:19
Fixed in 1.4.1

**Closed as completed by manuelgu** 2016-10-01 14:19 UTC
Labels: bug, confirmed

**Comment by gauderkd** [comment] 2016-10-03 18:04
Sweet, I switched permissions plugins in the end anyways but glad I could point this out!
