### ISSUE TITLE
Users having to use /discord toggle before usage

### ISSUE THREAD

**Issue by linuswillner** [manuelgu/DiscordMC#9] opened 2016-10-11 13:42 UTC
As it seems, for the bot to send any messages or the user be able to send anything, `discord toggle` has to be used. Before that the bot will not send messages in either direction.

Having the chat possibility be a thing per default could be nice.

**Comment by manuelgu** [comment] 2016-11-14 17:34
Cannot reproduce. Still an issue? Please also provide a `/discord debug`

**Comment by linuswillner** [comment] 2016-11-14 18:23
Issue seems to have been temporary. IDK what happened there.

**Comment by manuelgu** [comment] 2016-11-14 18:53
Okay, weird! Feel free to open up another issue in case it re-appears and I will investigate further!

**Comment by Collin-M** [comment] 2017-01-05 03:50
I am having this issue using version 1.4.8. Chat will not be sent to discord unless each user (with appropriate discordmc.chat permission node) types `/discord toggle`

**Comment by ministicraft** [comment] 2017-02-02 21:25
I am having this issue too using version 1.4.10

**Comment by manuelgu** [comment] 2017-02-02 21:59
@ministicraft is this also the case after the player relogs? did the player get `discordmc.chat` after the server was started with DiscordMC installed, with no restart in between?

**Comment by manuelgu** [comment] 2017-03-25 11:56
Fixed in recent version

**Closed as completed by manuelgu** 2017-03-25 11:56 UTC
Labels: bug
